---
- name: Check if certificate already exists.
  stat:
    path: /etc/letsencrypt/live/{{ _certbot_cert_item.domains | first }}/cert.pem

- name: Create webroot directory if it doesn't exist yet
  file:
    path: "{{ _certbot_cert_item.webroot | default(certbot_webroot) }}"
    state: directory
    group: www-data
    mode: 0750
  when: (_certbot_cert_item.webroot | default(certbot_webroot)) is not none

- name: Generate new certificate if one doesn't exist, one host at a time
  command: "{{ certbot_create_command }}"
  register: _certbot_generate_certificate
  throttle: 1

- name: Print reload message
  debug:
    msg:
      - "****"
      - "**** !!! MANUAL RELOAD NEEDED !!!"
      - "**** Configuration files changed, you have to..."
      - "**** 1. update your webserver configuration to use:"
      - "**** 1.1. certificate in /etc/letsencrypt/live/{{ _certbot_cert_item.domains | first }}/cert.pem"
      - "**** 1.2. private key in /etc/letsencrypt/live/{{ _certbot_cert_item.domains | first }}/privkey.pem"
      - "**** 2. and reload it"
      - "****"
  when: _certbot_generate_certificate.changed
