---
- name: Install Certbot from repository and related packages
  package:
    name: "{{ certbot_packages + ['cron'] }}"
    state: present

- name: systemctl disable --now certbot.timer
  systemd:
    name: certbot.timer
    enabled: false
    state: stopped

- name: Install Certbot plugin
  pip:
    name: "{{ certbot_plugins }}"
    executable: "{{ certbot_plugins_pip_executable }}"
