---
- name: Install Certbot from repository and related packages
  package:
    name: "{{ item }}"
    state: "present"
  loop: "{{ certbot_packages }}"

- name: Install Certbot plugin
  pip:
    name: "{{ item }}"
  loop: "{{ certbot_plugins }}"

- name: Install cron
  apt: name=cron state=present
