---
- name: "Install Certbot from repository and related packages"
  ansible.builtin.package:
    name: "{{ certbot_packages + ['cron'] }}"
    state: present

- name: "Systemctl disable --now certbot.timer"
  ansible.builtin.systemd:
    name: certbot.timer
    enabled: false
    state: stopped

- name: "Install Certbot plugin"
  ansible.builtin.pip:
    name: "{{ certbot_plugins }}"
    executable: "{{ certbot_plugins_pip_executable }}"
  when: certbot_plugins
