---
- name: Install Certbot from repository
  package:
    name: "{{ certbot_package }}"
    state: "present"

- name: Install Certbot plugin
  pip:
    name: "{{ item }}"
  loop: "{{ certbot_plugins }}"

- name: Install cron
  apt: name=cron state=present
