---
- name: reload_message
  debug:
    msg:
      - "****"
      - "**** !!! MANUAL RELOAD NEEDED !!!"
      - "**** Configuration files changed, you have to reload apache manually"
      - "****"
  when: not certbot_reload_apache
